---
version: "3.3"

services:
  tor_proxy:
    image: "bushido/tor_proxy:${VERSION_TAG}"
    container_name: ${TOR_PROXY_HOST}
    build: 
      context: .
      dockerfile: "./bushido.market/etc/tor/Dockerfile"
    environment:
      TOR_PROXY_ACCEPT: ${TOR_PROXY_ACCEPT}
    volumes:
      - tor:/tor/
    restart: unless-stopped
    # We do not need to expose any port because all the request are going
    # inside of the container network
    networks:
      bushido-net:
        ipv4_address: ${TOR_STATIC_IP}
  noKYC_web_server:
    image: "bushido/no_kyc:${VERSION_TAG}"
    container_name: ${NOKYC_API_HOST}
    build:
      context: .
      dockerfile: './bushido.market/etc/fastapi/Dockerfile'
    command: "/start-reload.sh"
    volumes:
      - ./bushido.market/src/app:/app/
    networks:
      bushido-net:
        ipv4_address: ${APP_STATIC_IP}
  bushido_db:
    container_name: ${NEO4J_HOST}
    image: neo4j:4.4.9
    volumes:
      # Mount the neo4j configuration file to container    
      - ./bushid.backend/database/neo4j/conf:/conf
      # Mount the data to container
      - ./bushid.backend/database/neo4j/data:/data
      - ./bushid.backend/database/neo4j/import:/import
      - ./bushid.backend/database/neo4j/logs:/logs
      - ./bushid.backend/database/neo4j/plugins:/plugins
    env_file: ./bushid.backend/database/.env
    networks:
       - ${BUSHIDO_NETWORK}
  bushido_web_server:
    container_name: ${BACKEND_HOST}
    image: "bushido/web_server:${VERSION_TAG}"
    depends_on: 
      - bushido_db
    build: 
      context: ./bushid.backend/deploy
    restart: "no"
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
       - ${BUSHIDO_NETWORK}

volumes:
  tor:
  nokyc-app:
# Create a network to add the nokyc-api IP in the /tor/torrc file
# We cannot add the container name because we get the following error
# Malformed IP "tor-proxy" in address pattern; rejecting.
networks:
  bushido-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}